export { default as Dress } from './Dress.vue'
export { default as HomePage } from './HomePage.vue'
export { default as Main } from '../components/Main.vue'
export { default as Tshirt } from './Tshirt.vue'
export { default as Trousers } from './Trousers.vue'
export { default as Skincare } from './Skincare.vue'
export { default as Parfum } from './Parfum.vue'
export { default as HomeDecoration } from './HomeDecoration.vue'
export { default as ManCatalog } from './ManCatalog.vue'
export { default as SunGlasses} from './SunGlasses.vue'
export { default as MenWatch } from './MenWatch.vue'
export { default as MenTshirt } from './MenTshirt.vue'
export {default as CardItem} from '../components/CardItem.vue'
export { default as CatalogPage} from './CatalogPage.vue'
export {default as Sidebar} from '../components/Sidebar.vue'
export {default as DataLoader} from '../components/DataLoader/DataLoader.vue'
export {default as ProductCard} from './ProductCard.vue'
export { default as Title } from '../components/Title.vue'
export { default as BaseButton } from '../components/BaseButton.vue'
export {default as PopUpWindow} from '../components/PopUpWindow.vue'
export {default as Basket} from './Basket.vue'
export { default as Input} from '../components/Input.vue'
export { default as BasketProduct} from '../components/BasketProduct.vue'
export { default as Product} from '../components/Product.vue'