export { default as Dress } from './Dress.vue'
export { default as HomePage } from './HomePage.vue'
export { default as Main } from '../components/Main.vue'
export { default as Tshirt } from './Tshirt.vue'
export { default as Trousers } from './Trousers.vue'
export { default as Shoes } from './Shoes.vue'
export { default as Sneakers } from './Sneakers.vue'
export { default as Bag } from './Bag.vue'
export { default as ManCatalog } from './ManCatalog.vue'
export { default as Electronic } from './Electronic.vue'
export { default as Texnic } from './Texnic.vue'
export { default as Sport } from './Sport.vue'
export {default as CardItem} from '../components/CardItem.vue'
