export { default as CardItem } from './CardItem.vue'
export { default as Main } from './Main.vue'
export { default as Header } from './Header.vue'
export { default as BaseButton } from './BaseButton.vue'
export { default as Svg } from './Svg.vue'
export { default as Title } from './Title.vue'
export { default as SidebarElements } from './SidebarElements.vue'
export { default as Sidebar } from './Sidebar.vue'
export { default as SidebarInfo } from './SidebarInfo.vue'
export { default as PopUpWindow } from './PopUpWindow.vue'
export { default as Input} from './Input.vue'
export { default as BasketProduct} from './BasketProduct.vue'
export {default as BreadCrumb} from './BreadCrumb.vue'